### ISSUE TITLE
What is the point of making a fork?

### ISSUE THREAD

**Issue by mak448a** [mono300genuine/discord-chatbot#1]
Just wondering, what’s better about this downstream repo besides a few minor changes? It’s easier to have one repo than two.

**Comment by mak448a** [comment]
And if there’s anything that you changed, could you make a pull request? I can update upstream with the new g4f package name and remove junk code. Thanks!

**Comment by mak448a** [comment]
@mono300genuine

**Comment by mono300genuine** [comment]
Nice to meet you @mak448a 
Thank you for reaching out.
I am interested in creating a Discord chatbot and came across this repository while looking for it.
I would like to contribute to this repository by sending a PR.
is it okay?

**Comment by mak448a** [comment]
Sure!

**Comment by mak448a** [comment]
I can also merge them manually and add you as a contributor, if you don’t have the time to send a pull request.

**Comment by mono300genuine** [comment]
okay.
no problem.

**Comment by mak448a** [comment]
Sorry, I looked into it more, and it looks like you'll have to create the pull request to be added as a contributor. @mono300genuine

**Comment by mono300genuine** [comment]
sure.

**Comment by mak448a** [comment]
By the way, do you know how all the commits got transferred over to your name? I'm wondering since another fork like this popped up. Could you fix this and add a fork notice #3?
![image](https://github.com/mono300genuine/discord-chatbot/assets/94062293/31b48dc7-1351-4139-ba49-3e8b1bdf7493)
