### ISSUE TITLE
Could you add information that this is a fork?

### ISSUE THREAD

**Issue by mak448a** [mono300genuine/discord-chatbot#2]
People seem to be starring this, when I think that this is supposed to be a fork for contributing? Please add information that links back to the original so that everyone can have an up to date version. Thanks

**Comment by mono300genuine** [comment]
@mak448a
i dont konw exactly how this thing happens
sorry for confusing because of my fork
really appolozies for my fork on this repo
could you updated readme.md to reflect your original link as you want?
if you pr, I will merge it.
sorry again.

**Comment by mak448a** [comment]
Thanks for fixing it!
